Repository SirGoodenough/HA_Blueprints, pull requests merged in 2023-10, with the labels that each got.

#20 Piper tts all message script
  Automations/door_open_tts_cloud_say_and_Piper_announcer_Piper_OR_nabu_casa_required.md
  Automations/door_open_tts_cloud_say_and_Piper_announcer_Piper_OR_nabu_casa_required.yaml
  Scripts/tts_All_Message_Script_Blueprint.md
  Scripts/tts_All_Message_Script_Blueprint.yaml
Labels: bug, documentation, Feature Request

#26 Update color_control_4_magic_cube.yaml
  Scripts/color_control_4_magic_cube.yaml
Labels: bug

#27 2023-10-31: Add Scalar to adjust the flow profile
  Automations/HumidifierWaterThrottleControl.md
  Automations/HumidifierWaterThrottleControl.yaml
Labels: enhancement
